pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        IMAGE_NAME = "obama_joseph-flask-app"
        DOCKERHUB_USERNAME = "josephxngx"
    }

    stages {

        stage('Clonage') {
            steps {
                echo 'Clonage du dépôt GitHub...'
                git branch: 'main',
                    url: 'https://github.com/Josephdata204/OBAMA_Joseph_flask-app.git'
            }
        }

        stage('Image') {
            steps {
                echo 'Construction de l image Docker...'
                sh 'docker build -t ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest .'
            }
        }

        stage('Publication') {
            steps {
                echo 'Publication sur DockerHub...'
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                sh 'docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest'
            }
        }
    }

    post {
        success {
            echo 'Pipeline exécuté avec succès !'
        }
        failure {
            echo 'Échec du pipeline.'
        }
    }
}
