name: CI/CD Pipeline - OBAMA Joseph

on:
  push:
    branches:
      - principal

jobs:
  Clonage:
    runs-on: ubuntu-latest
    steps:
      - name: Clonage du dépôt
        uses: actions/checkout@v3

  Image:
    runs-on: ubuntu-latest
    needs: Clonage
    steps:
      - name: Clonage du dépôt
        uses: actions/checkout@v3

      - name: Construction de l'image Docker
        run: docker build -t josephxngx/obama_joseph-flask-app:latest .

  Publication:
    runs-on: ubuntu-latest
    needs: Image
    steps:
      - name: Clonage du dépôt
        uses: actions/checkout@v3

      - name: Construction de l'image Docker
        run: docker build -t josephxngx/obama_joseph-flask-app:latest .

      - name: Connexion à DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Publication sur DockerHub
        run: docker push josephxngx/obama_joseph-flask-app:latest
